language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
  - redis
env:
  global:
    - TZ=Europe/Kiev
cache:
  directories:
    - eggs
before_install:
  - pip install python-coveralls
  - python2 bootstrap.py
  - mv openprocurement/auction/worker/tests/data/auction_worker_travis.yaml openprocurement/auction/worker/tests/data/auction_worker_defaults.yaml
install:
  - bin/buildout -N
  - curl -X PUT 0.0.0.0:5984/auctions
script:
  - bin/pytest openprocurement/auction/worker/tests/unit
after_success:
  - coveralls
