language: python
sudo: required
python:
  - "2.7"
services:
  - couchdb
  - redis
env:
  global:
    - TZ=Europe/Kiev
before_install:
  - pip install python-coveralls pytest==3.2.3
  - python2 bootstrap.py
  - mv openprocurement/auction/worker/tests/data/auction_worker_travis.yaml openprocurement/auction/worker/tests/data/auction_worker_defaults.yaml
install:
  - bin/buildout -N
  - curl -X PUT 0.0.0.0:5984/auctions
script:
  - bin/pytest openprocurement/auction/worker/tests/unit/
after_success:
  - coveralls
